# Single Dimension NumPy Array

In [3]:
import numpy as np
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [4]:
type(n1)

numpy.ndarray

# MultiDimension NumPy Array

In [9]:
import numpy as np
n2= np.array([[10,20,30,40,50],[10,80,90,60,50],[30,50,80,70,90],[20,30,50,70,90]])
n2

array([[10, 20, 30, 40, 50],
       [10, 80, 90, 60, 50],
       [30, 50, 80, 70, 90],
       [20, 30, 50, 70, 90]])

# Initialize NumPy array with zeros

In [12]:
n3=np.zeros((4,5))
n3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Initialization a array of matrix with full then

In [14]:
n4=np.full((4,5),9)
n4

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

# Initialization a array within a range.

In [18]:
n5=np.arange(10,20)
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

# Initialization of NumPy array within the random numbers

In [19]:
n7=np.random.randint(100,1000,10)
n7

array([653, 333, 405, 477, 682, 204, 575, 825, 588, 270])

In [20]:

n8=np.array([[10,20,30],[10,80,90],[30,50,80],[30,50,80]])
n8

array([[10, 20, 30],
       [10, 80, 90],
       [30, 50, 80],
       [30, 50, 80]])

In [21]:
n8.shape

(4, 3)

In [24]:
n8.shape=(3,4)
n8

array([[10, 20, 30, 10],
       [80, 90, 30, 50],
       [80, 30, 50, 80]])

# joining NumPy Array


In [26]:
import numpy as np
a=np.array([10,20,30])
b=np.array([30,50,90])

np.vstack((a,b))

array([[10, 20, 30],
       [30, 50, 90]])

In [27]:
np.hstack((a,b))

array([10, 20, 30, 30, 50, 90])

In [28]:
np.column_stack((a,b))

array([[10, 30],
       [20, 50],
       [30, 90]])

# NumPy intersection and difference

In [30]:
import numpy as np
x=np.array([10,20,30,40,50,60])
y=np.array([30,50,60,100,120,150])

np.intersect1d(x,y)

array([30, 50, 60])

In [32]:
np.setdiff1d(x,y)

array([10, 20, 40])

In [33]:
np.setdiff1d(y,x)

array([100, 120, 150])

# Addition of NumPy Arrays

In [34]:
import numpy as np
t=np.array([10,20])
s=np.array([30,50])

np.sum([t,s])

110

In [35]:
np.sum([t,s],axis=0)

array([40, 70])

In [36]:
np.sum([t,s],axis=1)

array([30, 80])

# NumPy array Mathematics

In [41]:
p=np.array([10,20,30])
p[0]+1

11

In [42]:
p/2

array([ 5., 10., 15.])

In [43]:
p*2


array([20, 40, 60])

In [44]:
p-2

array([ 8, 18, 28])

# NumPy math function

In [46]:
import numpy as np
nn=np.array([10,20,30,60])

np.mean(nn)

30.0

In [47]:
np.std(nn)

18.708286933869708

In [48]:
np.median(nn)

25.0

# saving and loading NumPy array

In [51]:
import numpy as np
n11=np.array([10,20,30,40,50])

np.save('Pranaya',n11)
np.load('Pranaya.npy')

array([10, 20, 30, 40, 50])